name: Demo CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Bước 1: In ra Xin chào
      - name: Say Hello
        run: echo "Xin chào CI/CD 🚀"

      # Bước 2: Checkout code từ GitHub
      - name: Checkout code
        uses: actions/checkout@v4

      # Bước 3: Đọc file README
      - name: Read README file
        run: cat README.md
